### ISSUE TITLE
Behaviorsearch exception for models using Level Space

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/behaviorsearch#4]
[bsearch-levelspace-bug.zip](https://github.com/NetLogo/behaviorsearch/files/8336177/bsearch-levelspace-bug.zip)
This error can be reproduced with a simpler model. I created a Level Space model based on the original bug report.

To reproduce the issue:

> Unpack the zip file
> Open the Behaviorsearch app (6.2.2)
> Open and run the file bsearch-ls-bug.bsearch

You should get an error dialog with the message: "Unexpected exception when attempting to run NetLogo.

Contents:

> bsearch.app.BehaviorSearchException: Unexpected exception while attempting to run NetLogo
> 	at bsearch.evaluation.SearchManager.computeFitnessBatch(SearchManager.java:121)
> 	at bsearch.algorithms.StandardGA.search(StandardGA.java:79)
> 	at bsearch.app.BehaviorSearch.runProtocol(BehaviorSearch.java:112)
> 	at bsearch.app.BehaviorSearch.runMultipleSearches(BehaviorSearch.java:51)
> 	at bsearch.app.BehaviorSearch.runWithOptions(BehaviorSearch.java:307)
> 	at bsearch.fx.ProgressController$TaskWorker.run(ProgressController.java:299)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at bsearch.fx.ProgressController$1.run(ProgressController.java:77)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
> 	at bsearch.nlogolink.BatchRunner.doBatchRun(BatchRunner.java:47)
> 	at bsearch.evaluation.SearchManager.computeFitnessBatch(SearchManager.java:223)
> 	at bsearch.evaluation.SearchManager.computeFitnessBatch(SearchManager.java:118)
> 	... 9 more
> Caused by: java.lang.NullPointerException
> 	at org.nlogo.ls.BackingModelManager.<init>(BackingModelManager.scala:20)
> 	at org.nlogo.ls.LevelSpace.<init>(LevelSpace.scala:76)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at java.lang.Class.newInstance(Class.java:442)
> 	at org.nlogo.workspace.JarLoader.extensionClassManager(JarLoader.scala:48)
> 	at org.nlogo.workspace.ExtensionManager.$anonfun$importExtension$8(ExtensionManager.scala:159)
> 	at scala.Option.getOrElse(Option.scala:189)
> 	at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:157)
> 	at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1(StructureParser.scala:74)
> 	at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1$adapted(StructureParser.scala:68)
> 	at scala.collection.immutable.List.foreach(List.scala:431)
> 	at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:68)
> 	at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:33)
> 	at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:17)
> 	at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
> 	at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
> 	at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
> 	at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
> 	at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
> 	at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:47)
> 	at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:54)
> 	at org.nlogo.headless.HeadlessModelOpener.openFromModel(HeadlessModelOpener.scala:50)
> 	at org.nlogo.headless.HeadlessWorkspace.openModel(HeadlessWorkspace.scala:550)
> 	at org.nlogo.headless.HeadlessWorkspace.open(HeadlessWorkspace.scala:517)
> 	at bsearch.nlogolink.ModelRunner.<init>(ModelRunner.java:43)
> 	at bsearch.nlogolink.ModelRunner.<init>(ModelRunner.java:18)
> 	at bsearch.nlogolink.ModelRunner$Factory.newModelRunner(ModelRunner.java:391)
> 	at bsearch.nlogolink.ModelRunner$Factory.acquireModelRunner(ModelRunner.java:379)
> 	at bsearch.nlogolink.ModelRunnerTask.call(ModelRunnerTask.java:17)
> 	at bsearch.nlogolink.ModelRunnerTask.call(ModelRunnerTask.java:5)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	... 1 more

Note: the Progress Dialog continues despite the error.

My system info:

> NetLogo 6.2.2 (December 8, 2021)
> Extension API version: 6.1
> OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
> operating system: Mac OS X 10.14.6 (x86_64 processor)
> Scala version 2.12.15
> Java heap: used = 16 MB, free = 273 MB, max = 910 MB
> 
> JOGL: (3D View not initialized)
> OpenGL Graphics: (3D View not initialized)

I am using Level Space 2.3.2

**Comment by brandesNW** [comment]
Bryan Head (primary creator of LevelSpace) suggested that from his recollection of the code, the fix requires the following change:

> This is happening because LevelSpace doesn't realize it's being run headlessly, so it tries to access the NetLogo application menu to inject the menu for opening child model code. If BehaviorSearch could set the Java system property `org.nlogo.preferHeadless` to `"true"`, that should take care of it. Here's the headless checking in LevelSpace: [https://github.com/NetLogo/LevelSpace/blob/50bd9da2a6f6c68f9be6b6f35118976da0a9de00/src/main/LevelSpace.scala#L31](https://urldefense.com/v3/__https://github.com/NetLogo/LevelSpace/blob/50bd9da2a6f6c68f9be6b6f35118976da0a9de00/src/main/LevelSpace.scala*L31__;Iw!!Dq0X2DkFhyF93HkjWTBQKhk!Fh5wS6dKUGsL4ee96wXgj8CqBHqVAAWzNWK4MgykpNNYX2QRuQpIl5T3e1g-wvWBXztoKgNFjA$)
> 
> It works in GUI BehaviorSpace because the NetLogo application menu is available there. Headless BehaviorSpace sets the above system property; the check was added so that LevelSpace could work there.
