### ISSUE TITLE
Behaviorsearch error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by RubensZimbres** [NetLogo/behaviorsearch#5]
Hello, I developed a NetLogo model with the following setup

https://drive.google.com/file/d/10lJQhk_RaCI6wUo7pLplh9pMr9P0pf3h/view?usp=sharing

And I'm trying to run Behaviorsearch optimization like this:

https://drive.google.com/file/d/1jLAZVpEv9xUUAPb_bcyB49xzzbIDdLLC/view?usp=sharing

The final measure is the average euclidean distance of the network:

`sqrt ( ( centroid-x - max ( [xcor] of turtles )) ^ 2 + ( centroid-y - max ( [ycor] of turtles )) ^ 2 )
`

The code uses the following extensions [ py nw arduino csv matrix ]

But I get the error "Unexpected exception" caused by java.lang.NullPointerException

https://drive.google.com/file/d/1MWLQaIcM7gSf6PgFyaDKj854n0H3uBX0/view?usp=sharing

Looks like something was not defined, But I can't find it. BehaviorSpace works perfectly with these configurations.

I'm using Ubuntu 20.04, Java 1.8 properly configured, I updated to 1.11, but it still does not work. 

An interesting behavior is that when I click "Load parameter ranges from model interface", nothing happens.

Any ideas what can be wrong ?

The full notebook is here: https://drive.google.com/file/d/1pWIr5a4H4b6dLKsMpPSuB-G40swXd83L/view?usp=sharing

The Behaviorsearch file is here: https://drive.google.com/file/d/1NlZwPUDqUGpzgF0yk__svSsqU3Tc2LY5/view?usp=sharing

The Behaviorsearch examples work perfectly. I don't know if this is something related to Chooser, Switch or Python, maybe it's a misconfiguration.

It does not look like something related to this other issue:

https://github.com/NetLogo/NetLogo/pull/1277

The error:

`
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at bsearch.nlogolink.BatchRunner.doBatchRun(BatchRunner.java:47)
	at bsearch.evaluation.SearchManager.computeFitnessBatch(SearchManager.java:223)
	at bsearch.evaluation.SearchManager.computeFitnessBatch(SearchManager.java:118)
	at bsearch.algorithms.StandardGA.search(StandardGA.java:79)
	at bsearch.app.BehaviorSearch.runProtocol(BehaviorSearch.java:112)
	at bsearch.app.BehaviorSearch.runMultipleSearches(BehaviorSearch.java:51)
	at bsearch.app.BehaviorSearch.runWithOptions(BehaviorSearch.java:307)
	at bsearch.fx.ProgressController$TaskWorker.run(ProgressController.java:299)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at bsearch.fx.ProgressController$1.run(ProgressController.java:77)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.nlogo.extensions.py.PythonExtension.runOnce(PythonExtension.scala:519)
	at org.nlogo.workspace.ExtensionManager.initializedClassManager(ExtensionManager.scala:196)
	at org.nlogo.workspace.ExtensionManager.$anonfun$importExtension$8(ExtensionManager.scala:159)
	at scala.Option.getOrElse(Option.scala:189)
	at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:157)
	at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1(StructureParser.scala:74)
	at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1$adapted(StructureParser.scala:68)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:68)
	at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:33)
	at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:17)
	at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
	at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
	at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
	at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
	at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
	at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:47)
	at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:54)
	at org.nlogo.headless.HeadlessModelOpener.openFromModel(HeadlessModelOpener.scala:50)
	at org.nlogo.headless.HeadlessWorkspace.openModel(HeadlessWorkspace.scala:550)
	at org.nlogo.headless.HeadlessWorkspace.open(HeadlessWorkspace.scala:517)
	at bsearch.nlogolink.ModelRunner.<init>(ModelRunner.java:43)
	at bsearch.nlogolink.ModelRunner.<init>(ModelRunner.java:18)
	at bsearch.nlogolink.ModelRunner$Factory.newModelRunner(ModelRunner.java:391)
	at bsearch.nlogolink.ModelRunner$Factory.acquireModelRunner(ModelRunner.java:379)
	at bsearch.nlogolink.ModelRunnerTask.call(ModelRunnerTask.java:17)
	at bsearch.nlogolink.ModelRunnerTask.call(ModelRunnerTask.java:5)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
bsearch.nlogolink.NetLogoLinkException: Unexpected exception while attempting to run NetLogo
	at bsearch.nlogolink.BatchRunner.doBatchRun(BatchRunner.java:64)
	at bsearch.evaluation.SearchManager.computeFitnessBatch(SearchManager.java:223)
	at bsearch.evaluation.SearchManager.computeFitnessBatch(SearchManager.java:118)
	at bsearch.algorithms.StandardGA.search(StandardGA.java:79)
	at bsearch.app.BehaviorSearch.runProtocol(BehaviorSearch.java:112)
	at bsearch.app.BehaviorSearch.runMultipleSearches(BehaviorSearch.java:51)
	at bsearch.app.BehaviorSearch.runWithOptions(BehaviorSearch.java:307)
	at bsearch.fx.ProgressController$TaskWorker.run(ProgressController.java:299)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at bsearch.fx.ProgressController$1.run(ProgressController.java:77)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at bsearch.nlogolink.BatchRunner.doBatchRun(BatchRunner.java:47)
	... 11 more
Caused by: java.lang.NullPointerException
	at org.nlogo.extensions.py.PythonExtension.runOnce(PythonExtension.scala:519)
	at org.nlogo.workspace.ExtensionManager.initializedClassManager(ExtensionManager.scala:196)
	at org.nlogo.workspace.ExtensionManager.$anonfun$importExtension$8(ExtensionManager.scala:159)
	at scala.Option.getOrElse(Option.scala:189)
	at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:157)
	at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1(StructureParser.scala:74)
	at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1$adapted(StructureParser.scala:68)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:68)
	at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:33)
	at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:17)
	at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
	at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
	at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
	at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
	at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
	at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:47)
	at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:54)
	at org.nlogo.headless.HeadlessModelOpener.openFromModel(HeadlessModelOpener.scala:50)
	at org.nlogo.headless.HeadlessWorkspace.openModel(HeadlessWorkspace.scala:550)
	at org.nlogo.headless.HeadlessWorkspace.open(HeadlessWorkspace.scala:517)
	at bsearch.nlogolink.ModelRunner.<init>(ModelRunner.java:43)
	at bsearch.nlogolink.ModelRunner.<init>(ModelRunner.java:18)
	at bsearch.nlogolink.ModelRunner$Factory.newModelRunner(ModelRunner.java:391)
	at bsearch.nlogolink.ModelRunner$Factory.acquireModelRunner(ModelRunner.java:379)
	at bsearch.nlogolink.ModelRunnerTask.call(ModelRunnerTask.java:17)
	at bsearch.nlogolink.ModelRunnerTask.call(ModelRunnerTask.java:5)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
bsearch.app.BehaviorSearchException: Unexpected exception while attempting to run NetLogo
	at bsearch.evaluation.SearchManager.computeFitnessBatch(SearchManager.java:121)
	at bsearch.algorithms.StandardGA.search(StandardGA.java:79)
	at bsearch.app.BehaviorSearch.runProtocol(BehaviorSearch.java:112)
	at bsearch.app.BehaviorSearch.runMultipleSearches(BehaviorSearch.java:51)
	at bsearch.app.BehaviorSearch.runWithOptions(BehaviorSearch.java:307)
	at bsearch.fx.ProgressController$TaskWorker.run(ProgressController.java:299)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at bsearch.fx.ProgressController$1.run(ProgressController.java:77)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at bsearch.nlogolink.BatchRunner.doBatchRun(BatchRunner.java:47)
	at bsearch.evaluation.SearchManager.computeFitnessBatch(SearchManager.java:223)
	at bsearch.evaluation.SearchManager.computeFitnessBatch(SearchManager.java:118)
	... 9 more
Caused by: java.lang.NullPointerException
	at org.nlogo.extensions.py.PythonExtension.runOnce(PythonExtension.scala:519)
	at org.nlogo.workspace.ExtensionManager.initializedClassManager(ExtensionManager.scala:196)
	at org.nlogo.workspace.ExtensionManager.$anonfun$importExtension$8(ExtensionManager.scala:159)
	at scala.Option.getOrElse(Option.scala:189)
	at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:157)
	at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1(StructureParser.scala:74)
	at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1$adapted(StructureParser.scala:68)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:68)
	at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:33)
	at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:17)
	at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
	at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
	at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
	at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
	at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
	at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:47)
	at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:54)
	at org.nlogo.headless.HeadlessModelOpener.openFromModel(HeadlessModelOpener.scala:50)
	at org.nlogo.headless.HeadlessWorkspace.openModel(HeadlessWorkspace.scala:550)
	at org.nlogo.headless.HeadlessWorkspace.open(HeadlessWorkspace.scala:517)
	at bsearch.nlogolink.ModelRunner.<init>(ModelRunner.java:43)
	at bsearch.nlogolink.ModelRunner.<init>(ModelRunner.java:18)
	at bsearch.nlogolink.ModelRunner$Factory.newModelRunner(ModelRunner.java:391)
	at bsearch.nlogolink.ModelRunner$Factory.acquireModelRunner(ModelRunner.java:379)
	at bsearch.nlogolink.ModelRunnerTask.call(ModelRunnerTask.java:17)
	at bsearch.nlogolink.ModelRunnerTask.call(ModelRunnerTask.java:5)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
`

**Comment by LaCuneta** [comment]
@RubensZimbres Thanks for reporting this and sorry you ran into it.  The core of the issue is that the Python extension isn't detecting that's it's being run outside of the NetLogo GUI and it's bombing out trying to add its menu item to the NetLogo app bar, which obviously doesn't exist.

There is a workaround, though.  In the `app/` folder of your NetLogo install, find and open the `Behaviorsearch.cfg` file in a text editor.  In the `[JVMOptions]` section add a line with `-Dorg.nlogo.preferHeadless=true`.  So the full section should look like:

```
[JVMOptions]
-Xmx1024m
-XX:+UseParallelGC
-Dfile.encoding=UTF-8
-Dorg.nlogo.preferHeadless=true
```

I tested that out and it got around the initial null pointer error.  Let me know if you have questions on it or still have issues. 

I'll work on getting a proper resolution added to the Python extension and similar extensions that attach themselves to the NetLogo GUI.

**Comment by RubensZimbres** [comment]
@LaCuneta yes, I noticed it was something related to Python. At first, I thought it was about the Python path not defined in Behaviorsearch, but not. Now I successfully ran the Behaviorsearch. Thanks very much for the solution, it worked perfectly. I'm very glad with NetLogo perfomance and features !

**Comment by RubensZimbres** [comment]
I'll close this issue, as it is solved.
